// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessTracker.API.Data;

#nullable disable

namespace ProcessTracker.API.Migrations
{
    [DbContext(typeof(ProcessTrackerDbContext))]
    partial class ProcessTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProcessTracker.API.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("ProcessTracker.API.Entities.ProcessDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProcessCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessCode")
                        .IsUnique();

                    b.ToTable("ProcessDefinitions");
                });

            modelBuilder.Entity("ProcessTracker.API.Entities.ProcessDefinitionProjectMapping", b =>
                {
                    b.Property<int>("ProcessDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("ProcessDefinitionId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProcessDefinitionProjectMappings");
                });

            modelBuilder.Entity("ProcessTracker.API.Entities.ProcessField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FieldType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<int?>("MinLength")
                        .HasColumnType("int");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProcessDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessDefinitionId", "FieldName")
                        .IsUnique();

                    b.ToTable("ProcessFields");
                });

            modelBuilder.Entity("ProcessTracker.API.Entities.ProcessRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProcessDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessDefinitionId");

                    b.HasIndex("ServiceItemId")
                        .IsUnique();

                    b.ToTable("ProcessRecords", t =>
                        {
                            t.HasCheckConstraint("CK_ProcessRecord_DataJson", "ISJSON(DataJson) = 1");
                        });
                });

            modelBuilder.Entity("ProcessTracker.API.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProcessTracker.API.Entities.ServiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProcessDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ProcessDefinitionId");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.ToTable("ServiceItems");
                });

            modelBuilder.Entity("ProcessTracker.API.Entities.Application", b =>
                {
                    b.HasOne("ProcessTracker.API.Entities.Project", "Project")
                        .WithMany("Applications")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProcessTracker.API.Entities.ProcessDefinitionProjectMapping", b =>
                {
                    b.HasOne("ProcessTracker.API.Entities.ProcessDefinition", "ProcessDefinition")
                        .WithMany("ProcessDefinitionProjectMappings")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcessTracker.API.Entities.Project", "Project")
                        .WithMany("ProcessDefinitionProjectMappings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessDefinition");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProcessTracker.API.Entities.ProcessField", b =>
                {
                    b.HasOne("ProcessTracker.API.Entities.ProcessDefinition", "ProcessDefinition")
                        .WithMany("ProcessFields")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessDefinition");
                });

            modelBuilder.Entity("ProcessTracker.API.Entities.ProcessRecord", b =>
                {
                    b.HasOne("ProcessTracker.API.Entities.ProcessDefinition", "ProcessDefinition")
                        .WithMany("ProcessRecords")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcessTracker.API.Entities.ServiceItem", "ServiceItem")
                        .WithOne("ProcessRecord")
                        .HasForeignKey("ProcessTracker.API.Entities.ProcessRecord", "ServiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessDefinition");

                    b.Navigation("ServiceItem");
                });

            modelBuilder.Entity("ProcessTracker.API.Entities.ServiceItem", b =>
                {
                    b.HasOne("ProcessTracker.API.Entities.Application", "Application")
                        .WithMany("ServiceItems")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcessTracker.API.Entities.ProcessDefinition", "ProcessDefinition")
                        .WithMany("ServiceItems")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("ProcessDefinition");
                });

            modelBuilder.Entity("ProcessTracker.API.Entities.Application", b =>
                {
                    b.Navigation("ServiceItems");
                });

            modelBuilder.Entity("ProcessTracker.API.Entities.ProcessDefinition", b =>
                {
                    b.Navigation("ProcessDefinitionProjectMappings");

                    b.Navigation("ProcessFields");

                    b.Navigation("ProcessRecords");

                    b.Navigation("ServiceItems");
                });

            modelBuilder.Entity("ProcessTracker.API.Entities.Project", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("ProcessDefinitionProjectMappings");
                });

            modelBuilder.Entity("ProcessTracker.API.Entities.ServiceItem", b =>
                {
                    b.Navigation("ProcessRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
